#!/bin/bash

BASE_DIR="resources/views/admin/auto-ecole"

mkdir -p "$BASE_DIR/chapitres"
touch "$BASE_DIR/chapitres/index.blade.php"
touch "$BASE_DIR/chapitres/create.blade.php"
touch "$BASE_DIR/chapitres/show.blade.php"
touch "$BASE_DIR/chapitres/edit.blade.php"
mkdir -p "$BASE_DIR/codes-caisse"
touch "$BASE_DIR/codes-caisse/index.blade.php"
touch "$BASE_DIR/codes-caisse/create.blade.php"
touch "$BASE_DIR/codes-caisse/show.blade.php"
mkdir -p "$BASE_DIR/config"
touch "$BASE_DIR/config/index.blade.php"
touch "$BASE_DIR/dashboard.blade.php"
mkdir -p "$BASE_DIR/lecons"
touch "$BASE_DIR/lecons/index.blade.php"
touch "$BASE_DIR/lecons/create.blade.php"
touch "$BASE_DIR/lecons/show.blade.php"
touch "$BASE_DIR/lecons/edit.blade.php"
mkdir -p "$BASE_DIR/modules"
touch "$BASE_DIR/modules/index.blade.php"
touch "$BASE_DIR/modules/create.blade.php"
touch "$BASE_DIR/modules/show.blade.php"
touch "$BASE_DIR/modules/edit.blade.php"
mkdir -p "$BASE_DIR/paiements"
touch "$BASE_DIR/paiements/index.blade.php"
touch "$BASE_DIR/paiements/show.blade.php"
touch "$BASE_DIR/paiements/rapport.blade.php"
mkdir -p "$BASE_DIR/quiz"
touch "$BASE_DIR/quiz/index.blade.php"
touch "$BASE_DIR/quiz/create.blade.php"
touch "$BASE_DIR/quiz/show.blade.php"
touch "$BASE_DIR/quiz/edit.blade.php"
mkdir -p "$BASE_DIR/sessions"
touch "$BASE_DIR/sessions/index.blade.php"
touch "$BASE_DIR/sessions/create.blade.php"
touch "$BASE_DIR/sessions/edit.blade.php"
mkdir -p "$BASE_DIR/users"
touch "$BASE_DIR/users/index.blade.php"
touch "$BASE_DIR/users/show.blade.php"
touch "$BASE_DIR/users/edit.blade.php"
echo "All view files created successfully."
